name: Add new issues to org project

on:
  issues:
    types:
      - opened

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v0.5.0
        with:
          # You can target a project in a different organization
          # to the issue
          project-url: https://github.com/orgs/dropecho/projects/4
          github-token: ${{ secrets.GH_PROJECTS_ACTIONS_TOKEN }}
